AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CIDRSubnet1:
    Type: String
    Default: "10.10.0.0/24"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: Enter the CIDR Range for your VPC
    MaxLength: "18"
    MinLength: "9"

  CIDRSubnet2:
    Type: String
    Default: "10.10.1.0/24"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: Enter the CIDR Range for your VPC
    MaxLength: "18"
    MinLength: "9"

  CIDRVPC:
    Type: String
    Default: "10.10.0.0/16"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: Enter the CIDR Range for your VPC
    MaxLength: "18"
    MinLength: "9"

  DesiredCapacity:
    Type: Number
    Default: "2"
    Description: Number of instances to launch in your ECS cluster

  ECSAMI:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ecs/optimized-ami/amazon-linux/recommended/image_id
    Description: AMI ID

  ECSClusterName:
    Type: String
    Default: rexray-efs
    Description: ECS Cluster Name

  InstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
    ConstraintDescription: must be a valid EC2 instance type.
    Description: The EC2 instance type

  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances

  SSHLocation:
    Type: String
    Default: "0.0.0.0/0"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: " The IP address range that can be used to SSH to the EC2 instances"
    MaxLength: "18"
    MinLength: "9"

Resources:
  CWLogsGroup:
    Type: "AWS::Logs::LogGroup"

  ContainerInstances:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Metadata:
      "AWS::CloudFormation::Init":
        config:
          commands:
            "01_add_instance_to_cluster":
              command: !Sub echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
            "02_start_ecs_agent":
              command: start ecs
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub "[main]\nstack=${AWS::StackId}\nregion=${AWS::Region}\n"
              group: root
              mode: 256
              owner: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub "[cfn-auto-reloader-hook]\ntriggers=post.update\npath=Resources.ContainerInstances.Metadata.AWS::CloudFormation::Init\naction=/opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ContainerInstances\n"
          packages:
            yum:
              aws-cli: []
              ecs-init: []
              jq: []
              nfs-utils: []
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref ECSAMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - Ref: EFSSecurityGroup
        - Ref: InstanceSecurityGroup
      UserData: !Base64
        "Fn::Sub": "#!/bin/bash\nyum install -y amazon-efs-utils\nyum install -y nfs-utils\nyum install -y aws-cfn-bootstrap\n/opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ContainerInstances\n/opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSAutoScalingGroup\n#open file descriptor for stderr\nexec 2>>/var/log/ecs/ecs-agent-install.log\nset -x\n#verify that the agent is running\nuntil curl -s http://localhost:51678/v1/metadata\ndo\nsleep 1\ndone\n#install the Docker volume plugin\ndocker plugin install rexray/efs REXRAY_PREEMPT=true EFS_REGION=${AWS::Region} EFS_SECURITYGROUPS=${EFSSecurityGroup} --grant-all-permissions\n#restart the ECS agent\nstop ecs \nstart ecs\n"

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - Ref: EC2Role

  EC2Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
        - "arn:aws:iam::aws:policy/AmazonElasticFileSystemReadOnlyAccess"
      Path: /
      Policies:
        - PolicyName: RexrayVolumesPolicy
          PolicyDocument: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [{\n    \"Effect\": \"Allow\",\n    \"Action\": [\n      \"ec2:AttachVolume\",\n      \"ec2:CreateVolume\",\n      \"ec2:CreateSnapshot\",\n      \"ec2:CreateTags\",\n      \"ec2:DeleteVolume\",\n      \"ec2:DeleteSnapshot\",\n      \"ec2:DescribeAvailabilityZones\",\n      \"ec2:DescribeInstances\",\n      \"ec2:DescribeVolumes\",\n      \"ec2:DescribeVolumeAttribute\",\n      \"ec2:DescribeVolumeStatus\",\n      \"ec2:DescribeSnapshots\",\n      \"ec2:CopySnapshot\",\n      \"ec2:DescribeSnapshotAttribute\",\n      \"ec2:DetachVolume\",\n      \"ec2:ModifySnapshotAttribute\",\n      \"ec2:ModifyVolumeAttribute\",\n      \"ec2:DescribeTags\"\n    ],\n    \"Resource\": \"*\"\n  }]\n}\n"
        - PolicyName: RexrayEFSPolicy
          PolicyDocument: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [{\n    \"Effect\": \"Allow\",\n    \"Action\": [\n      \"elasticfilesystem:CreateFileSystem\",\n      \"elasticfilesystem:CreateMountTarget\",\n      \"ec2:DescribeSubnets\",\n      \"ec2:DescribeNetworkInterfaces\",\n      \"ec2:CreateNetworkInterface\",\n      \"elasticfilesystem:CreateTags\",\n      \"elasticfilesystem:DeleteFileSystem\",\n      \"elasticfilesystem:DeleteMountTarget\",\n      \"ec2:DeleteNetworkInterface\",\n      \"elasticfilesystem:DescribeFileSystems\",\n      \"elasticfilesystem:DescribeMountTargets\"\n    ],\n    \"Resource\": \"*\"\n  }]\n}\n"

  ECSAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      AvailabilityZones:
        - "Fn::Select":
            - "0"
            - "Fn::GetAZs": !Ref "AWS::Region"
        - "Fn::Select":
            - "1"
            - "Fn::GetAZs": !Ref "AWS::Region"
      DesiredCapacity: "2"
      LaunchConfigurationName: !Ref ContainerInstances
      MaxSize: "2"
      MinSize: "2"
      Tags:
        - Key: Name
          PropagateAtLaunch: "true"
          Value: ECS rexray host
      VPCZoneIdentifier:
        - Ref: Subnet1
        - Ref: Subnet2
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: "1"
        MinInstancesInService: "1"
        PauseTime: PT15M
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: "true"

  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ECSClusterName

  ECSServiceAutoScalingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: ecs-service-autoscaling
          PolicyDocument: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [{\n    \"Effect\": \"Allow\",\n    \"Action\": [\n      \"application-autoscaling:*\",\n      \"cloudwatch:DescribeAlarms\",\n      \"cloudwatch:PutMetricAlarm\",\n      \"ecs:DescribeServices\",\n      \"ecs:UpdateService\"\n    ],\n    \"Resource\": \"*\"\n  }]\n}  \n"

  EFSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable EFS access via port 2049
      SecurityGroupIngress:
        - CidrIp: !Ref CIDRVPC
          FromPort: "2049"
          IpProtocol: tcp
          ToPort: "2049"
      VpcId: !Ref VPC

  GatewayToInternet:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: !Ref SSHLocation
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"
        - CidrIp: !Ref SSHLocation
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
      VpcId: !Ref VPC

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Application
          Value: !Ref "AWS::StackName"
        - Key: Network
          Value: Public

  NLBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 80
      Protocol: TCP

  NetworkLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Scheme: internet-facing
      Subnets:
        - Ref: Subnet1
        - Ref: Subnet2
      Type: network

  PublicRoute:
    Type: "AWS::EC2::Route"
    DependsOn:
      - PublicRouteTable
      - InternetGateway
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    DependsOn:
      - VPC
    Properties:
      Tags:
        - Key: Application
          Value: !Ref "AWS::StackName"
        - Key: Network
          Value: Public
      VpcId: !Ref VPC

  PublicSubnet1RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    DependsOn:
      - Subnet1
      - PublicRouteTable
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref Subnet1

  PublicSubnet2RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    DependsOn:
      - Subnet2
      - PublicRouteTable
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref Subnet2

  Subnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select
        - "0"
        - "Fn::GetAZs": !Ref "AWS::Region"
      CidrBlock: !Ref CIDRSubnet1
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  Subnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select
        - "1"
        - "Fn::GetAZs": !Ref "AWS::Region"
      CidrBlock: !Ref CIDRSubnet2
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref CIDRVPC
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Volume-Driver VPC

  WebTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 80
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPC

  ApplicationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CWLogsGroup
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          MountPoints:
            - ContainerPath: /var/www
              SourceVolume: rexray-efs-vol
          Image: tiffanyfay/space:apache
          Essential: true
          Name: space
      Memory: '512'
      Family: rexray-efs
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      Cpu: '512'
      Volumes:
        - Name: rexray-efs-vol
          DockerVolumeConfiguration:
            Autoprovision: true
            Scope: shared
            Driver: rexray/efs

Outputs:
  AWSRegion:
    Description: The name of the region where the stack was launched
    Value: !Ref "AWS::Region"

  AvailabilityZones:
    Description: The AZ where the instances are deployed
    Value: !Join
      - ","
      - - "Fn::GetAtt":
            - Subnet1
            - AvailabilityZone
        - "Fn::GetAtt":
            - Subnet2
            - AvailabilityZone

  CWLogGroupName:
    Description: The name of the CWLogs group
    Value: !Ref CWLogsGroup

  ECSClusterName:
    Description: The name of the ECS cluster
    Value: !Ref ECSCluster

  EFSSecurityGroupId:
    Description: The ID of security group for EFS port 2049 access
    Value: !Ref EFSSecurityGroup

  InstanceSecurityGroupId:
    Description: The ID of security group that the instances are members of
    Value: !Ref InstanceSecurityGroup

  NLBDNSName:
    Description: The DNS name of the NLB
    Value: !GetAtt NetworkLoadBalancer.DNSName

  NLBName:
    Description: The name of the NLB
    Value: !GetAtt NetworkLoadBalancer.LoadBalancerName

  StackName:
    Description: The name of the CloudFormation Stack
    Value: !Ref "AWS::StackName"

  SubnetIDs:
    Description: The IDs of the subnets that the instances are associated with
    Value: !Join
      - ","
      - - Ref: Subnet1
        - Ref: Subnet2

  VPCID:
    Description: The VPC where the stack was launched
    Value: !Ref VPC

  WebTargetGroupArn:
    Description: The ARN of the Web Target Group
    Value: !Ref WebTargetGroup
