AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Elastic Container Service (ECS) definition for TinyDevCRM

Resources:
  ApplicationCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub "${AWS::StackName}-cluster"
