AWSTemplateFormatVersion: "2010-09-09"

Description: Data layer for EC2 autoscaling groups for TinyDevCRM. This is necessary in order to avoid tying data with compute layer lifecycles (such as deletion). EBS for database persist files, and EFS for static files.

Resources:
  ApplicationBlockStore:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select
        - 0
        - "Fn::GetAZs": ""
      Size: 1
      Tags:
        - Key: Name
          Value: tinydevcrm-ebs
      VolumeType: gp2

  ApplicationEFSFilesystem:
    Type: "AWS::EFS::FileSystem"
    Properties:
      FileSystemTags:
        - Key: Name
          Value: tinydevcrm-efs