AWSTemplateFormatVersion: "2010-09-09"

Description: Secrets management layer for TinyDevCRM

Resources:
  CustomerMasterKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: Customer master key for AWS Secrets Management Service
      EnableKeyRotation: true
      Enabled: true
      KeyPolicy:
        Id: tinydevcrm-kms-policy
        Statement:
          - Sid: AllowRootAccountAccessToKey
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
        Version: "2012-10-17"

  DjangoApplicationSecret:
    Type: "AWS::SecretsManager::Secret"
    DependsOn:
      - CustomerMasterKey
    Properties:
      Description: Secret key for Django application managed by AWS Secrets Management Service
      GenerateSecretString:
        ExcludeCharacters: "\"@/\\"
        GenerateStringKey: SECRET_KEY
        PasswordLength: 30
        SecretStringTemplate: "{}"
      KmsKeyId: !Ref CustomerMasterKey
      Name: tinydevcrm-django-secret-key

  PostgreSQLDatabaseSecret:
    Type: "AWS::SecretsManager::Secret"
    DependsOn:
      - CustomerMasterKey
    Properties:
      Description: Secret key for PostgreSQL database managed by AWS Secrets Management Service
      GenerateSecretString:
        ExcludeCharacters: "\"@/\\"
        GenerateStringKey: POSTGRES_PASSWORD
        PasswordLength: 30
        SecretStringTemplate: "{}"
      KmsKeyId: !Ref CustomerMasterKey
      Name: tinydevcrm-postgresql-password