AWSTemplateFormatVersion: '2010-09-09'

Description: Identity and access management layer for TinyDevCRM

Parameters:
    RootAWSAccountID:
        Type: String
        Description: Root AWS account ID

Resources:
    AdminRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: Allow
                        Principal: {
                            "AWS": !Sub "arn:aws:iam::${RootAWSAccountID}:root"
                        }
                        Action:
                            - 'sts:AssumeRole'
            ManagedPolicyArns:
                - 'arn:aws:iam::aws:policy/AdministratorAccess'
            Description: Temporarily elevates IAM user to admin-level privileges, except to change IAM permissions
            MaxSessionDuration: 3600
            RoleName: tinydevcrm-admin

    AdminGroup:
        Type: AWS::IAM::Group
        DependsOn:
            - AdminRole
        Properties:
            GroupName: tinydevcrm-administrators
            Policies:
                - PolicyName: AssumeAdminRole
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    - Effect: Allow
                      Action: 'sts:AssumeRole'
                      Resource: !GetAtt AdminRole.Arn

    RequireMFAPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            Description: Force IAM user to apply MFA before enabling resource control.
            ManagedPolicyName: tinydevcrm-RequireMFAPolicy
            # From: https://gist.github.com/mixja/15d2969efe806680c2a4b0059daaf697
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Sid: AllowAllUsersToListAccounts
                      Effect: Allow
                      Action:
                        - iam:ListAccountAliases
                        - iam:GetAccountPasswordPolicy
                        - iam:ListUsers
                        - iam:GetAccountSummary
                      Resource:
                        - '*'
                    - Sid: AllowIndividualUserToSeeTheirAccountInformationAndCreateAccessKey
                      Effect: Allow
                      Action:
                        - iam:ChangePassword
                        - iam:CreateLoginProfile
                        - iam:DeleteLoginProfile
                        - iam:GetAccountPasswordPolicy
                        - iam:GetLoginProfile
                        - iam:UpdateLoginProfile
                        - iam:CreateAccessKey
                        - iam:ListAccessKeys
                      Resource:
                        - !Sub arn:aws:iam::${RootAWSAccountID}:user/${!aws:username}
                    - Sid: AllowIndividualUserToListTheirMFA
                      Effect: Allow
                      Action:
                        - iam:ListVirtualMFADevices
                        - iam:ListMFADevices
                      Resource:
                        - !Sub arn:aws:iam::${RootAWSAccountID}:mfa/*
                        - !Sub arn:aws:iam::${RootAWSAccountID}:user/${!aws:username}
                    - Sid: AllowIndividualUserToManageTheirMFA
                      Effect: Allow
                      Action:
                        - iam:CreateVirtualMFADevice
                        - iam:EnableMFADevice
                        - iam:ResyncMFADevice
                      Resource:
                        - !Sub arn:aws:iam::${RootAWSAccountID}:mfa/${!aws:username}
                        - !Sub arn:aws:iam::${RootAWSAccountID}:user/${!aws:username}
                    - Sid: DenyEverythingExceptForBelowUnlessMFAd
                      Effect: Deny
                      NotAction:
                        - iam:ListVirtualMFADevices
                        - iam:ListMFADevices
                        - iam:ListUsers
                        - iam:ListAccountAliases
                        - iam:CreateVirtualMFADevice
                        - iam:EnableMFADevice
                        - iam:ResyncMFADevice
                        - iam:ChangePassword
                        - iam:CreateLoginProfile
                        - iam:DeleteLoginProfile
                        - iam:GetAccountPasswordPolicy
                        - iam:GetAccountSummary
                        - iam:GetLoginProfile
                        - iam:UpdateLoginProfile
                      Resource: '*'
                      Condition:
                        'Null':
                          'aws:MultiFactorAuthAge': 'true'
                    - Sid: DenyIamAccessToOtherAccountsUnlessMFAd
                      Effect: Deny
                      Action:
                        - iam:CreateVirtualMFADevice
                        - iam:DeactivateMFADevice
                        - iam:DeleteVirtualMFADevice
                        - iam:EnableMFADevice
                        - iam:ResyncMFADevice
                        - iam:ChangePassword
                        - iam:CreateLoginProfile
                        - iam:DeleteLoginProfile
                        - iam:GetAccountPasswordPolicy
                        - iam:GetLoginProfile
                        - iam:UpdateLoginProfile
                        - iam:CreateAccessKey
                        - iam:ListAccessKeys
                      NotResource:
                        - !Sub arn:aws:iam::${RootAWSAccountID}:mfa/${!aws:username}
                        - !Sub arn:aws:iam::${RootAWSAccountID}:user/${!aws:username}
                      Condition:
                        'Null':
                            'aws:MultiFactorAuthAge': 'true'

    UserGroup:
        Type: AWS::IAM::Group
        DependsOn:
            - RequireMFAPolicy
        Properties:
            GroupName: tinydevcrm-users
            ManagedPolicyArns:
                - !Ref RequireMFAPolicy
