AWSTemplateFormatVersion: "2010-09-09"

Description:  Compute layer for EC2 + ECS autoscaling groups for TinyDevCRM. Uses public VPC subnets and a public-facing load balancer.

Parameters:
  EC2DesiredCapacity:
    Type: Number
    Default: '2'
    Description: Average number of EC2 instances to launch in the ECS cluster.

  EC2MaximumCapacity:
    Type: Number
    Default: '6'
    Description: Maximum number of EC2 instances to launch in the ECS cluster.

  ECSAMI:
    Description: ID for the ECS-optimized EC2 AMI, updated to Amazon Linux 2.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

  EC2InstanceType:
    Type: String
    Default: t2.medium
    Description: EC2 instance type.

Resources:
