AWSTemplateFormatVersion: '2010-09-09'

Description: Secrets management layer for TinyDevCRM

Resources:
    KMSKey:
        Type: AWS::KMS::Key
        Properties:
            Description: Customer master key for AWS Secrets Management Service
            Enabled: true
            EnableKeyRotation: true
            KeyPolicy:
                - Sid: tinydevcrm-kms-policy
                  Effect: Allow
                  Principal:
                    AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
                  Action:
                    - kms:*
                  Resource: '*'
