AWSTemplateFormatVersion: '2010-09-09'

Description: Identity and access management layer for TinyDevCRM

Parameters:
    RootAWSAccountID:
        Type: String
        Description: Root AWS account ID

Resources:
    # AdminUser:
    #     Type: AWS::IAM::User
    #     Groups:
    #     LoginProfile:
    #     ManagedPolicyArns:
    #     Path:
    #     PermissionsBoundary:
    #     Policies:
    #     Tags:
    #     UserName:
    AdminRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: Allow
                        Principal: {
                            "AWS": !Sub "arn:aws:iam::${RootAWSAccountID}:root"
                        }
                        Action:
                            - 'sts:AssumeRole'
            ManagedPolicyArns:
                - 'arn:aws:iam::aws:policy/AdministratorAccess'
            Description: Temporarily elevates IAM user to admin-level privileges, except to change IAM permissions
            MaxSessionDuration: 3600
            RoleName: tinydevcrm-admin

    # AdminGroup:
    #     Type: AWS::IAM::Group
    #     Properties:
    #         GroupName:
    #         ManagedPolicyArns:
    #         Path:
    #         Policies:
    # UserGroup:
    #     Type: AWS::IAM::Group
    #     Properties:
    #         GroupName:
    #         ManagedPolicyArns:
    #         Path:
    #         Policies:
